site_name: Antcar's Blogger
theme:
  name: material
  palette:
    scheme: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
    - 'index.md'
    - 'about.md'
    - 'profile.md'
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 繁體中文
      link: /zh/ 
      lang: zh
plugins:
    - blog
