site_name: The Epic Antcar Blog
repo_url: https://github.com/antcar0929/blogger
edit_uri: edit/main/files
docs_dir: 'files'
site_author: Antcar
copyright: Antcar Ent. LLC


#It's nav time
nav:
    - Introduction: 'intro.md'
    - 'about.md'
    - 'Issue Tracker': 'https://example.com/'
