site_name: Antcar's Blogger
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    
  font:
    text: Fredoka One
nav:
    - 'index.md'
    - 'profile.md'
extra:
  generator: false
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 繁體中文
      link: /zh/ 
      lang: zh
  
  consent:
    title: Cookie eatie
    description: >- 
      Antcar loves cookies, and he need yours!
      He needs cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether others
      find what they're searching for! (Tip: eat chips ahoy!)
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  
copyright: Copyright &copy; &curyear Antcar
