site_name: Antcar's Blogger
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    
  features:
    - navigation.tabs
nav:
    - 'index.md'
    - 'profile.md'
extra:
  generator: false
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 繁體中文
      link: /zh/ 
      lang: zh

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  
copyright: Copyright &copy; &curyear Antcar
